import StyleDictionary from 'style-dictionary';

// ── Custom format: :root { base tokens } + :root[data-theme="X"] { ... } ──
StyleDictionary.registerFormat({
  name: 'css/fuse-with-themes',
  format: ({ dictionary }) => {
    const isTheme = (t) => t.path[0] === 'theme';
    const baseTokens  = dictionary.allTokens.filter(t => !isTheme(t));
    const themeTokens = dictionary.allTokens.filter(isTheme);

    // Group theme tokens by theme name (second path segment)
    const themeMap = new Map();
    for (const t of themeTokens) {
      const [, name, ...rest] = t.path;
      if (!themeMap.has(name)) themeMap.set(name, []);
      themeMap.get(name).push({ key: rest.join('-'), value: t.$value });
    }

    const lines = [
      '/* Auto-generated by Style Dictionary — do not edit */',
      '',
      ':root {',
    ];

    for (const t of baseTokens) {
      lines.push(`  --fuse-${t.path.join('-')}: ${t.$value};`);
    }
    lines.push('}', '');

    for (const [theme, tokens] of themeMap) {
      lines.push(`:root[data-theme="${theme}"] {`);
      for (const { key, value } of tokens) {
        lines.push(`  --fuse-${key}: ${value};`);
      }
      lines.push('}', '');
    }

    return lines.join('\n');
  },
});

const sd = new StyleDictionary({
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: 'fuse',
      buildPath: 'packages/core/src/lib/tokens/generated/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/fuse-with-themes',
        },
      ],
    },
    scss: {
      transformGroup: 'scss',
      prefix: 'fuse',
      buildPath: 'packages/core/src/lib/tokens/generated/',
      files: [
        {
          destination: '_variables.scss',
          format: 'scss/variables',
          filter: (token) => token.path[0] !== 'theme',
        },
      ],
    },
    ts: {
      transformGroup: 'js',
      prefix: 'fuse',
      buildPath: 'packages/core/src/lib/tokens/generated/',
      files: [
        {
          destination: 'tokens.ts',
          format: 'javascript/es6',
          filter: (token) => token.path[0] !== 'theme',
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();
